### ISSUE TITLE
VirusTotal report

### ISSUE THREAD

**Issue by Geniusssmit** [led-mirage/VoivoClip#1]
それはなんとかできないのか？
https://www.virustotal.com/gui/file/36b7d660568f8974ee66d5288c5c9b4fe5981b30f654ccfc1f1c6a4ddacbb991

**Comment by led-mirage** [comment]
ウィルス対策ソフトに誤検知される問題は、pyinstallerでexeファイルを作成しているためだと思われますが、なかなか解決するのは難しそうです。python.exeでスクリプトを直接実行すれば問題はでないと思いますが、使い勝手が悪くなるのは否めません。

**Comment by led-mirage** [comment]
PyInstallerをローカルでビルドしなおして、多少改善しました（VIrusTotalで5,6個検出程度）。
今のところこれ以上は難しそうなので、一旦クローズさせていただきます。
