### ISSUE TITLE
漢字の読み方を変える方法

### ISSUE THREAD

**Issue by Geniusssmit** [led-mirage/VoivoClip#2]
voicevoxって人名の漢字をいつも変な読み方にするんですよね。冬馬を「ふゆば」みたいに。それを「とうま」にする方法がありますか？ないならそれはリクエストです😀

**Comment by led-mirage** [comment]
VOICEVOX本体で設定できます。
「設定」－「読み方＆アクセント辞書」　（ver 0.18.0の場合）

VOICEVOX Engineを使用されている場合は、API経由で自力で登録する必要があります。
UIがないので（探せば誰かが作ってるかもですが）、少し難しいかもしれません。

**Comment by Geniusssmit** [comment]
ありがとうございます！
