### ISSUE TITLE
文章分割処理により、行単位で処理する正規表現の挙動が正しく保証されていない

### ISSUE THREAD

**Issue by JiaChen-Zeng** [led-mirage/VoivoClip#3]
ノベルゲームで、主人公のセリフと地の文だけ読み上げる用に使う想定です。今この不具合によりこのような使い方はおそらく不可能です。

下記のように正規表現で処理を行いたいです。下記サイトでの結果は私の予期しているもので間違いありません。ですがVoivoClipでは同じ結果にはなっていません。
https://regex101.com/r/ayD8dP/1

下記文章分割のところで `。` で分けしまっているのが原因だと思われます。テキストが長過ぎるとボイス生成の時間がかかりすぎるからそうしているかと思いますが、ボイス生成用のセンテンス分けを正規表現の処理を行ったあとで処理にするように順番を変えていただければ直るかと思います。
https://github.com/led-mirage/VoivoClip/blob/9d2861b0229a3d96de427eb8a93edf6b12b04739/main_window.py#L272

よろしくお願いします。

**Comment by led-mirage** [comment]
ご報告ありがとうございます。
v0.3.1で修正しました。
お試しくださいませ。

**Comment by JiaChen-Zeng** [comment]
ご修正ありがとうございます。ちゃんと読み上げができるようになりました👍
